name: Test Build

on:
  push:
    branches: main
    paths:
      - "**.h"
      - "**.cpp"
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: e44d60e6bf0964064bf69667cd9f3e91dc383c7c

jobs:
  test-build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset:
          - debug
          - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Run CMake
        uses: lukka/run-cmake@v10.6
        with:
          configurePreset: build-${{ matrix.preset }}-msvc
          buildPreset: ${{ matrix.preset }}-msvc

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.2
        with:
          event-type: format-event
